# Generated by Django 3.0.2 on 2020-04-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linemanager',
            name='Departments_under',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminDashboard.Departments'),
        ),
    ]
