# Generated by Django 3.0.2 on 2020-05-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0003_approve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='leave_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'rejected'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
    ]
