# Generated by Django 3.0.2 on 2020-05-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0004_auto_20200512_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
