# Generated by Django 2.1.2 on 2020-06-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0005_auto_20200517_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='leave_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
    ]
