# Generated by Django 3.0.6 on 2020-07-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0006_auto_20200628_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutiveDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
