# Generated by Django 3.0.6 on 2020-07-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0007_executivedirector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='leave_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
