# Generated by Django 3.0.6 on 2020-07-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0008_auto_20200702_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approve',
            name='leave_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=20, null=True),
        ),
    ]
