# Generated by Django 3.0.2 on 2020-04-17 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminDashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReferenceId', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('LeaveType', models.CharField(choices=[('Annual', 'Annual'), ('Sick', 'Sick'), ('Maternity ', 'Maternity '), ('Paternity', 'Paternity'), ('Compassionate', 'Compassionate'), ('Terminal / Long term illness ', 'Terminal / Long term illness '), ('Study leave with pay ', 'Study leave with pay '), ('Leave without pay ', 'Leave without pay ')], max_length=300, null=True)),
                ('DateApplied', models.DateField(auto_now=True)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('OutstandingLeaveDays', models.IntegerField(null=True)),
                ('NumberOfDaystaken', models.DateField()),
                ('empDepartment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminDashboard.Departments')),
                ('empDirector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminDashboard.Director')),
                ('empDirectorate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminDashboard.Directories')),
            ],
        ),
    ]
