# Generated by Django 3.0.2 on 2020-04-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveform',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='leaveform',
            name='slug',
            field=models.SlugField(default='test'),
            preserve_default=False,
        ),
    ]
