# Generated by Django 3.0.2 on 2020-04-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0002_auto_20200418_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='slug',
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='ReferenceId',
            field=models.SlugField(),
        ),
    ]
