# Generated by Django 3.0.2 on 2020-04-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0004_auto_20200418_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='ReferenceId',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
