# Generated by Django 3.0.2 on 2020-04-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0005_auto_20200419_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='slug',
        ),
    ]
