# Generated by Django 3.0.2 on 2020-04-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0006_remove_leaveform_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='ReferenceId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
