# Generated by Django 3.0.2 on 2020-04-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0007_auto_20200419_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='ReferenceId',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
