# Generated by Django 3.0.2 on 2020-04-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0008_auto_20200419_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveform',
            name='slug',
            field=models.SlugField(default='sure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveform',
            name='ReferenceId',
            field=models.AutoField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
