# Generated by Django 3.0.2 on 2020-04-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0009_auto_20200419_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveform',
            name='ReferenceId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
