# Generated by Django 3.0.2 on 2020-04-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0010_auto_20200419_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveform',
            name='slug',
        ),
    ]
