# Generated by Django 3.0.2 on 2020-04-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0002_linemanager_departments_under'),
        ('employeeDashboard', '0011_remove_leaveform_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveForm',
            new_name='Leaves',
        ),
    ]
