# Generated by Django 3.0.2 on 2020-04-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0012_auto_20200426_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='DateApplied',
            field=models.DurationField(max_length=20, null=True),
        ),
    ]
