# Generated by Django 3.0.2 on 2020-05-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0013_auto_20200427_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='DateApplied',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
