# Generated by Django 3.0.2 on 2020-05-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0014_auto_20200505_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='DateApplied',
            field=models.DateField(),
        ),
    ]
