# Generated by Django 3.0.2 on 2020-05-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0015_auto_20200505_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='NumberOfDaystaken',
            field=models.IntegerField(null=True),
        ),
    ]
