# Generated by Django 3.0.2 on 2020-05-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0016_auto_20200512_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='Status_dr',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='leaves',
            name='Status_ed',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='leaves',
            name='Status_lm',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'rejected'), ('Pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
