# Generated by Django 3.0.2 on 2020-05-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0017_auto_20200517_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='Status_dr',
            new_name='Approval_by_Director',
        ),
        migrations.RenameField(
            model_name='leaves',
            old_name='Status_ed',
            new_name='Approval_by_Executive_Director',
        ),
        migrations.RenameField(
            model_name='leaves',
            old_name='Status_lm',
            new_name='Approval_by_Line_Manager',
        ),
    ]
