# Generated by Django 3.0.2 on 2020-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0018_auto_20200517_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaves',
            name='ReferenceId',
        ),
        migrations.AddField(
            model_name='leaves',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
