# Generated by Django 3.0.2 on 2020-05-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0019_auto_20200517_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaves',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
