# Generated by Django 3.0.6 on 2020-07-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0023_auto_20200702_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='OutstandingLeaveDays',
            field=models.IntegerField(default=30, null=True),
        ),
    ]
