# Generated by Django 3.0.8 on 2020-08-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0025_leaves_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaves',
            name='DateApplied',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='OutstandingLeaveDays',
            field=models.IntegerField(default=26),
        ),
        migrations.AlterField(
            model_name='leaves',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/files/'),
        ),
    ]
