# Generated by Django 3.0.8 on 2020-08-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0026_auto_20200803_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
