# Generated by Django 3.0.8 on 2020-08-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeDashboard', '0027_leaves_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaves',
            old_name='status',
            new_name='cancellation_status',
        ),
    ]
