# Generated by Django 3.0.8 on 2020-07-30 14:57

from django.db import migrations, models
import uuid
from UsersAuth.models import Account


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0001_initial'),
    ]

    def gen_uuid(apps, schema_editor):
        for row in Account.objects.all():
            row.slug = uuid.uuid4()
            row.save()

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.SlugField(default=uuid.uuid4),
            preserve_default=True,
        ),
        migrations.RunPython(gen_uuid),

        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
