# Generated by Django 3.0.8 on 2020-08-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0003_auto_20200730_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='OutstandingLeaveDays',
            field=models.IntegerField(default=0),
        ),
    ]
