# Generated by Django 3.0.8 on 2020-08-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0004_account_outstandingleavedays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='OutstandingLeaveDays',
            field=models.IntegerField(null=True),
        ),
    ]
