# Generated by Django 3.0.8 on 2020-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0006_auto_20200813_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
