# Generated by Django 3.0.8 on 2020-08-20 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0007_account_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='start_of_month_tracker',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
