# Generated by Django 3.0.8 on 2020-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0008_account_start_of_month_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='start_of_month_tracker',
            field=models.DateTimeField(),
        ),
    ]
