# Generated by Django 3.0.8 on 2020-08-20 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0009_auto_20200820_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='start_of_month_tracker',
        ),
    ]
